### ISSUE TITLE
fehlerhafter Eintrag im Feld bikes_allowed in trips.txt

### ISSUE THREAD

**Issue by sebastianknopf** [mfdz/demo-mitfahrbank-gtfs#1]
Für die in trips.txt definierten Fahrten soll die Fahrradmitnahme explizit ausgeschlosen werden. Der Eintrag bikes_allowed = 0 führt gem. aktueller GTFS-Referenz allerdings dazu, dass die Fahrradmitnahme als "Unbekannt" gekennzeichnet wird, wordurch der optimistische Fahrgast irrtümlicherweise schließen könnte, dass die Fahrradmitnahme möglich sei. Der Eintrag bikes_allowed = 2 würde die Fahrradmitnahme - wie eigentlich gewollt - explizit ausschliesen.
Ansonsten sehr interessantes Projekt :-)

**Comment by hbruch** [comment]
Danke für den Hinweis!
